version: '3.8'
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: idlemania
      POSTGRES_USER: idlemania
      POSTGRES_PASSWORD: idlemania
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
