spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/idlemania}
spring.datasource.username=${DATABASE_USERNAME:idlemania}
spring.datasource.password=${DATABASE_PASSWORD:idlemania}
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
server.port=${PORT:8080}
